/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import logica.Cliente;
import logica.Mesa;
import logica.Reserva;
/**
 *
 * @author Daisy Ccaceres
 */
public class Menu extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private List<Reserva> reservas;           
    private boolean[][] disponibilidad;      
    private List<Mesa> mesas;
    /**
     * Creates new form Menu
     */
    public Menu() {
    initComponents();
    inicializarVariables();  
    tableModel = new DefaultTableModel();
    tableModel.addColumn("ID Reserva");
    tableModel.addColumn("Nombre Cliente");
    tableModel.addColumn("Mesa");
    tableModel.addColumn("Horario");

    jTable1.setModel(tableModel);
    }
    
        private void inicializarVariables() {
        // iniciar lista de las reservas
        reservas = new ArrayList<>();

        //iniciar la lista de las mesas 
        mesas = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            mesas.add(new Mesa(i,4)); // mesas del 0 al 9
        }

        // iniciar la matriz de disponibilidad
        disponibilidad = new boolean[10][24];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 24; j++) {
                disponibilidad[i][j] = true; // todas las mesas al principio esten disponibles
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Reservas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RegistrarReserva = new javax.swing.JButton();
        ModificarReserva = new javax.swing.JButton();
        EliminarReserva = new javax.swing.JButton();
        DisponibilidadReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(166, 208, 221));

        Reservas.setBackground(new java.awt.Color(0, 0, 0));
        Reservas.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 65)); // NOI18N
        Reservas.setForeground(new java.awt.Color(0, 0, 0));
        Reservas.setText("RESERVAS LA VIE GOURMET");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giu/download__2_-removebg-preview (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reservas))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        RegistrarReserva.setBackground(new java.awt.Color(0, 0, 0));
        RegistrarReserva.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        RegistrarReserva.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarReserva.setText("Registrar Reserva");
        RegistrarReserva.setBorder(null);
        RegistrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarReservaActionPerformed(evt);
            }
        });

        ModificarReserva.setBackground(new java.awt.Color(0, 0, 0));
        ModificarReserva.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        ModificarReserva.setForeground(new java.awt.Color(255, 255, 255));
        ModificarReserva.setText("Modificar Reserva");
        ModificarReserva.setBorder(null);
        ModificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarReservaActionPerformed(evt);
            }
        });

        EliminarReserva.setBackground(new java.awt.Color(0, 0, 0));
        EliminarReserva.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        EliminarReserva.setForeground(new java.awt.Color(255, 255, 255));
        EliminarReserva.setText("Eliminar reserva");
        EliminarReserva.setBorder(null);
        EliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarReservaActionPerformed(evt);
            }
        });

        DisponibilidadReserva.setBackground(new java.awt.Color(0, 0, 0));
        DisponibilidadReserva.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        DisponibilidadReserva.setForeground(new java.awt.Color(255, 255, 255));
        DisponibilidadReserva.setText("Disponibilidad Reservas");
        DisponibilidadReserva.setBorder(null);
        DisponibilidadReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponibilidadReservaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(EliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModificarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RegistrarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DisponibilidadReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(EliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(RegistrarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))))
                    .addComponent(DisponibilidadReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarReservaActionPerformed
      String nombre = JOptionPane.showInputDialog("Ingrese el nombre del cliente:");
      String telefono = JOptionPane.showInputDialog("Ingrese el telefono del cliente:");

    while (telefono.length() != 8 || !esNumero(telefono)) {
        JOptionPane.showMessageDialog(null, "El telefono debe tener 8 caracteres");
        telefono = JOptionPane.showInputDialog("Ingrese el telefono del cliente:");
    }

    int personas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de personas:"));

    while (personas < 1 || personas > 4) {
        JOptionPane.showMessageDialog(null, "La cantidad de personas debe ser entre 1 y 4");
        personas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de personas:"));
    }

    Cliente nuevoCliente = new Cliente(nombre, telefono, personas);

    int mesaIndex = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de la mesa (0 - 9):"));

    while (mesaIndex < 0 || mesaIndex >= mesas.size()) {
        JOptionPane.showMessageDialog(null, "Numero de mesa no valido. Tiene que  ser entre 0 y 9.");
        mesaIndex = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de la mesa (0 - 9):"));
    }

    String horario = JOptionPane.showInputDialog("Ingrese el horario (HH:MM):");

    while (!esFormatoHoraValido(horario)) {
        JOptionPane.showMessageDialog(null, "El formato de la hora no es valido. Tiene ser HH:mm (24 horas).");
        horario = JOptionPane.showInputDialog("Ingrese el horario (HH:MM):");
    }

    int horarioIndex = Integer.parseInt(horario.split(":")[0]);
    if (disponibilidad[mesaIndex][horarioIndex]) {
        Mesa mesaSeleccionada = mesas.get(mesaIndex);
        mesaSeleccionada.setDisponible(false);
        disponibilidad[mesaIndex][horarioIndex] = false;

        Reserva nuevaReserva = new Reserva(nuevoCliente, mesaSeleccionada, horario);
        reservas.add(nuevaReserva);

        tableModel.addRow(new Object[]{
            nuevaReserva.getIdReserva(),
            nuevoCliente.getNombre(),
            mesaSeleccionada.getNumeroMesa(),
            horario
        });

        JOptionPane.showMessageDialog(null, "Reserva realizada correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "La mesa no esta disponible en ese horario");
    }
    
    
    }                                            
    private boolean esNumero(String cadena) {
    // verifica que los caracteres sean numeros
    for (int i = 0; i < cadena.length(); i++) {
        if (cadena.charAt(i) < '0' || cadena.charAt(i) > '9') {
            return false;
        }
    }
    return true;
    }
    
    private boolean esFormatoHoraValido(String hora) {
    if (hora.length() != 5) return false;

    String[] partes = hora.split(":");
    if (partes.length != 2) return false;

    int horas = 0;
    int minutos = 0;

    for (int i = 0; i < partes[0].length(); i++) {
        if (partes[0].charAt(i) < '0' || partes[0].charAt(i) > '9') return false;
        horas = horas * 10 + (partes[0].charAt(i) - '0');
    }

    for (int i = 0; i < partes[1].length(); i++) {
        if (partes[1].charAt(i) < '0' || partes[1].charAt(i) > '9') return false;
        minutos = minutos * 10 + (partes[1].charAt(i) - '0');
    }

    return horas >= 0 && horas < 24 && minutos >= 0 && minutos < 60;
    }

    private int obtenerHoraIndex(String hora) {
    String[] partes = hora.split(":");
    return Integer.parseInt(partes[0]);

    }//GEN-LAST:event_RegistrarReservaActionPerformed

    private void EliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarReservaActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_EliminarReservaActionPerformed

    private void DisponibilidadReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponibilidadReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisponibilidadReservaActionPerformed

    private void ModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarReservaActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_ModificarReservaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisponibilidadReserva;
    private javax.swing.JButton EliminarReserva;
    private javax.swing.JButton ModificarReserva;
    private javax.swing.JButton RegistrarReserva;
    private javax.swing.JLabel Reservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
